version: "3.7"

volumes:
  cache:
    driver: local

services:
  backend:
    build: .
    ports:
      - "8081:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
      nominatim:
        condition: service_started
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/telebot
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      TOKEN: "6645685311:AAEv2S99I2KCXcJa8ZtEZHpLxVKO3_fL-6I"
#    networks:
#      - proxynet

  #  DATABASES
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telebot
      PGDATA: /data/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    restart: always
    ports:
      - "8091:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
      #      PBF_URL: https://download.geofabrik.de/russia-latest.osm.pbf
      #      REPLICATION_URL: https://download.geofabrik.de/russia-updates/
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
#    shm_size: 1gb
#    networks:
#      - proxynet

networks:
  default:
    name: nominatim

#networks:
#  proxynet:
#    name: custom_network
