from src.statemachine.state.constructor.ConstructorMenuState import ConstructorMenuState
from src.statemachine.state.constructor.DietState import DietState
from src.statemachine.state.constructor.GeneratorState import GeneratorState